In [1]:
import numpy as np
sd = np.array([1,2,3,4],dtype=np.int8)
print(sd.itemsize)

1


In [3]:
import numpy as np
l1 = [1,2,3]
x = np.asarray(l1)
print(x)

[1 2 3]


In [11]:
import numpy as np
a = np.arange(10)
s = slice(1,8,2)
b = a[s]
print(b)

[1 3 5 7]


In [6]:
import numpy as np
jk = np.arange(10)
kl = jk[2:7:2]
print(kl)

[2 4 6]


In [7]:
import numpy as np 
a = np.arange(0,60,5) 
a = a.reshape(3,4) 
print('Original array is:') 
print(a)
print('\n') 
print('Modified array is:') 
for x in np.nditer(a):
    print(x)

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Modified array is:
0
5
10
15
20
25
30
35
40
45
50
55


In [8]:
import numpy as np 
a = np.array([0,30,45,60,90]) 
print('Array containing sine values:') 
sin = np.sin(a*np.pi/180) 
print(sin) 
print('\n') 
print('Compute sine inverse of angles. Returned values are in radians.')
inv = np.arcsin(sin) 
print(inv)
print('\n')
print('Check result by converting to degrees:')
print(np.degrees(inv))
print('\n')
print('arccos and arctan functions behave similarly:')
cos = np.cos(a*np.pi/180) 
print(cos) 
print('\n')
print('Inverse of cos:')
inv = np.arccos(cos)
print(inv)
print('\n')
print('In degrees:') 
print(np.degrees(inv))
print('\n') 
print('Tan function:')
tan = np.tan(a*np.pi/180) 
print(tan)
print('\n') 
print('Inverse of tan:') 
inv = np.arctan(tan) 
print(inv)
print('\n') 
print('In degrees:')
print(np.degrees(inv))


Array containing sine values:
[0.         0.5        0.70710678 0.8660254  1.        ]


Compute sine inverse of angles. Returned values are in radians.
[0.         0.52359878 0.78539816 1.04719755 1.57079633]


Check result by converting to degrees:
[ 0. 30. 45. 60. 90.]


arccos and arctan functions behave similarly:
[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]


Inverse of cos:
[0.         0.52359878 0.78539816 1.04719755 1.57079633]


In degrees:
[ 0. 30. 45. 60. 90.]


Tan function:
[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


Inverse of tan:
[0.         0.52359878 0.78539816 1.04719755 1.57079633]


In degrees:
[ 0. 30. 45. 60. 90.]


In [10]:
import numpy as np
a = np.array([1.0,5.55, 123, 0.567, 25.532]) 
print('Original array:') 
print(a) 
print('\n') 
print('After rounding:') 
print(np.around(a)) 
print(np.around(a, decimals = 2)) 


Original array:
[  1.      5.55  123.      0.567  25.532]


After rounding:
[  1.   6. 123.   1.  26.]
[  1.     5.55 123.     0.57  25.53]
