In [1]:
from sklearn.datasets import load_iris 
iris = load_iris()
X = iris.data 
y = iris.target 
feature_names = iris.feature_names 
target_names = iris.target_names 
print("Feature names:", feature_names) 
print("Target names:", target_names) 
print("\nFirst 10 rows of X:\n", X[:10])


Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target names: ['setosa' 'versicolor' 'virginica']

First 10 rows of X:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


In [2]:
from sklearn.datasets import load_iris 
iris = load_iris()
X = iris.data 
y = iris.target
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size = 0.3, random_state = 1 )
print(X_train.shape)
print(X_test.shape)
print(y_train.shape) 
print(y_test.shape)


(105, 4)
(45, 4)
(105,)
(45,)


In [5]:
from sklearn.datasets import load_iris 
iris = load_iris() 
X = iris.data
y = iris.target
from sklearn.model_selection  import train_test_split 
X_train, X_test, y_train,y_test = train_test_split( X, y, test_size = 0.4, random_state=1 )
from sklearn.neighbors import KNeighborsClassifier 
from sklearn import metrics 
classifier_knn = KNeighborsClassifier(n_neighbors = 3)
classifier_knn.fit(X_train, y_train) 
y_pred = classifier_knn.predict(X_test) # Finding accuracy by comparing actual response values(y_test)with predicted response
 
print("Accuracy:", metrics.accuracy_score(y_test, y_pred)) # Providing sample data and the model will make prediction out of that data
sample = [[5, 5, 3, 2], [2, 4, 3, 5]] 
preds = classifier_knn.predict(sample)
pred_species = [iris.target_names[p] for p in preds]
print("Predictions:", pred_species)


Accuracy: 0.9833333333333333
Predictions: ['versicolor', 'virginica']


In [8]:
import numpy as np
from sklearn import preprocessing 
input_data = np.array( [[2.1, -1.9, 5.5], [-1.5, 2.4, 3.5], [0.5, -7.9, 5.6], [5.9, 2.3, -5.8]] ) 
data_binarized=preprocessing.Binarizer(threshold=0.5).transform(input_data) 
print("\nBinarized data:\n", data_binarized)



Binarized data:
 [[1. 0. 1.]
 [0. 1. 1.]
 [0. 0. 1.]
 [1. 1. 0.]]
