In [1]:
import numpy as np
num1 = np.array([12,13,14,15])
print(num1)

[12 13 14 15]


In [2]:
import numpy as np
arr2 = np.array([[1,2],[3,4]])
print(arr2)

[[1 2]
 [3 4]]


In [3]:
import numpy as np
arr2 = np.array([1,2,3],dtype=complex)
print(arr2)

[1.+0.j 2.+0.j 3.+0.j]


In [4]:
import numpy as np
a2 = np.array([[4,5,6],[7,8,9]])
print(a2.shape)

(2, 3)


In [5]:
import numpy as np
arr3 = np.array([[1,2,4],[7,9,10]])
arr3.shape = (3,2)
print(arr3)

[[ 1  2]
 [ 4  7]
 [ 9 10]]


In [6]:
import numpy as np
arr4 = np.array([[4,5,6],[7,10,11]])
b = arr4.reshape(3,2)
print(b)

[[ 4  5]
 [ 6  7]
 [10 11]]


In [8]:
import numpy as np
ar4 = np.arange(10)
print(ar4)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
import numpy as np
a = np.arange(24)
b = a.reshape(2,4,3)
print(b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]
